### ISSUE TITLE
Colocar tudo no wpbr-geouser

### ISSUE THREAD

**Issue by espellcaste** [wpbrasil/wpbr-mapa#10]
Eu venho utilizando o mapa em uma versão modificada em um projeto que estou trabalhando e lá eu coloquei tudo no plugin, ao invés de tema.

Tem alguns tickets que são bacanas aqui e que até já fiz para o projeto que estou trabalho, como o #7  por exemplo. Porém antes de sugerir algo, queria fazer uma sugestão de colocar tudo no wpbr-geouser, ao invés de ficar o tema aqui e o plugin lá separado.

O que vocês acham?

**Comment by eduardozulian** [comment]
@espellcaste, parece algo interessante, né? Quer fazer um PR com essa ideia pra gente ver como que fica? :smile:

**Comment by espellcaste** [comment]
(y)

**Comment by espellcaste** [comment]
@eduardozulian Estou precisando de uma sugestão, no meu projeto estou usando o BuddyPress e estou integrando com ele. No caso, aqui é diferente. 

Acredito que precisa ser definido onde ficará esse mapa. Seria melhor um shortcode?

**Comment by eduardozulian** [comment]
@espellcaste Acho que uma função mesmo resolve. Depois atualizamos e colocamos um shortcode se for o caso. Melhor, não?

**Comment by espellcaste** [comment]
OK! (y) 

Adicionei agora pouco um PR no WP-GeoUser. Feedback welcome!

**Comment by vmassuchetto** [comment]
Tentei atualizar o tema do site pra revisão b2a0ecd52ad3b89b4229c0d965e98a442012cbf8 e todos os pins ficaram zoados. Alguns com a logo do WP e outros com o pin vermelhinho e magrelo do Google Maps. Voltei a revisão pra d663c45e3d0601ceef5f5b3c9456a1a9ff4233e1

**Comment by eduardozulian** [comment]
@vmassuchetto: vamos pro #11 discutir isso?

**Comment by espellcaste** [comment]
Obrigado por aceitar o PR lá. Irei agora integrar a parte do front com a função como foi sugerido.

**Comment by eduardozulian** [comment]
Vou fechar esse tópico, @espellcaste. Tudo bem por você? :smile:

**Comment by espellcaste** [comment]
+1
